CREATE TABLE TB_ANSWERS (
       ANSWERS_ID           INTEGER NOT NULL,
       POLL_ID              INTEGER NOT NULL,
       ANSWER_TEXT          VARCHAR(200) NULL,
       HIT                  INTEGER NULL,
       INITIAL_HIT          INTEGER NULL,
       CONSTRAINT PK_ANSWER
              PRIMARY KEY NONCLUSTERED (ANSWERS_ID, POLL_ID)
);


CREATE TABLE TB_CUSTOM_QUERY (
       QUERY_ID             VARCHAR(20) NOT NULL,
       QUERY_TXT            VARCHAR(200) NOT NULL,
       CONSTRAINT PK_TB_CUSTOM_QUERY
              PRIMARY KEY NONCLUSTERED (QUERY_ID)
);


CREATE TABLE TB_NEWS (
       CONTENT_ID        	INTEGER NOT NULL ,
       TITLE                VARCHAR(255) NULL,
       SUBTITLE             VARCHAR(255) NULL,
       BODY                 TEXT NULL,
       CONSTRAINT PK_TB_NEWS
              PRIMARY KEY NONCLUSTERED (CONTENT_ID)
);


CREATE TABLE TB_NEWS_LINK (
       LINK_ID              INTEGER NOT NULL,
       NEWS_ID              INTEGER NOT NULL,
       URL                  VARCHAR(255) NULL,
       NEWS_LINK_TITLE      VARCHAR(255) NULL,
       ALT                  VARCHAR(255) NULL,
       CONSTRAINT PK_TB_NEWS_LINK
              PRIMARY KEY NONCLUSTERED (LINK_ID, NEWS_ID)
);


CREATE TABLE TB_NEWS_PICTURE (
       PICTURE_ID           INTEGER NOT NULL,
       NEWS_ID              INTEGER NOT NULL,
       URL                  VARCHAR(255) NULL,
       ALT                  VARCHAR(255) NULL,
       PICTURE_NAME         VARCHAR(255) NULL,
       CONSTRAINT PK_TB_NEWS_PICTURE
              PRIMARY KEY NONCLUSTERED (PICTURE_ID, NEWS_ID)
);


CREATE TABLE TB_POLL (
       CONTENT_ID           INTEGER NOT NULL,
       DESCRIPTION          VARCHAR(100) NULL,
       QUESTION             VARCHAR(200) NULL,
       QUESTION_TYPE        INTEGER NULL,
       CONSTRAINT PK_TB_POLL
              PRIMARY KEY NONCLUSTERED (CONTENT_ID)
);


CREATE TABLE TB_POLL_USER (
       POLL_ID              INTEGER NOT NULL,
       USER_ID              VARCHAR(20) NOT NULL,
       CONSTRAINT PK_TB_POLL_USER PRIMARY KEY NONCLUSTERED (USER_ID, POLL_ID)
);

CREATE TABLE TB_CONTENT (
       CONTENT_ID        INTEGER NOT NULL,
       STATUS_ID         INTEGER NOT NULL,
       CREATION_DATE        DATETIME NOT NULL,
       RELEASE_DATE         DATETIME NULL,
       APPROVAL_DATE        DATETIME NULL,
       PUBLISH_DATE         DATETIME NULL,
       EXPIRATION_DATE      DATETIME NULL,
       DRAFT_DATE           DATETIME NULL,
       DRAFT_USER_ID        VARCHAR(20) NULL,
       RELEASE_USER_ID      VARCHAR(20) NULL,
       APPROVE_USER_ID      VARCHAR(20) NULL,
       MODULE_ID            VARCHAR(50) NULL,
       CONSTRAINT PK_TB_CONTENT
              PRIMARY KEY NONCLUSTERED (CONTENT_ID)
);

CREATE TABLE TB_CONTENT_PERMISSION (
       CONTENT_ID              INTEGER NOT NULL,
       PRINCIPAL            VARCHAR(50) NOT NULL,
       PRINCIPAL_TYPE		   VARCHAR(20) NOT NULL,
       READ_PERMISSION			INTEGER NOT NULL,
       WRITE_PERMISSION			INTEGER NOT NULL,
       CONSTRAINT PK_TB_CONTENT_PERMISSION PRIMARY KEY NONCLUSTERED (PRINCIPAL, CONTENT_ID, PRINCIPAL_TYPE),
       CONSTRAINT CONTENT_READ_PERMISSION_CHECK CHECK (READ_PERMISSION in (0, 1)),
       CONSTRAINT CONTENT_WRITE_PERMISSION_CHECK CHECK (WRITE_PERMISSION in (0, 1)),
       CONSTRAINT CONTENT_PRINCIPAL_TYPE_CHECK CHECK (PRINCIPAL_TYPE in ('USER', 'GROUP'))
);


CREATE TABLE TB_CONTENT_STATUS (
       STATUS_ID         INTEGER NOT NULL,
       DESCRIPTION          VARCHAR(20) NOT NULL,
       CONSTRAINT PK_TB_CONTENT_STATUS
              PRIMARY KEY NONCLUSTERED (STATUS_ID)
);

CREATE TABLE TB_DIARY (
       CONTENT_ID           INTEGER NOT NULL,
       SUBJECT              VARCHAR(100) NULL,
       MESSAGE_DATE         DATETIME NULL,
       MESSAGE              TEXT NULL,
       CONSTRAINT PK_TB_DIARY
              PRIMARY KEY NONCLUSTERED (CONTENT_ID)
);

CREATE TABLE TB_MESSAGE (
       CONTENT_ID        	INTEGER NOT NULL,
       SUBJECT              VARCHAR(100) NULL,
       MESSAGE_DATE         DATETIME NULL,
       MESSAGE              TEXT NULL,
       CONSTRAINT PK_TB_MESSAGE
              PRIMARY KEY NONCLUSTERED (CONTENT_ID)
);

CREATE TABLE TB_CONTAINER_SCHEDULE (
	SCHEDULE_ID 			INTEGER NOT NULL ,
	SCHEDULE_NAME	 		VARCHAR(250),
	CONTAINER_NAME			VARCHAR(30),
	CONTAINER_TYPE			VARCHAR(20),
	POSITION 				INTEGER,
	URL 					VARCHAR(250),
	CONTENT_ID				INTEGER,
	PUBLISH_DATE        	DATETIME NULL,
    EXPIRATION_DATE      	DATETIME NULL,
	STATUS               	INTEGER DEFAULT 1 NULL,
	CONSTRAINT PK_TB_CONTAINER_SCHEDULE PRIMARY KEY (SCHEDULE_ID)
);
                             
CREATE TABLE TB_POPUP_SCHEDULE (
	SCHEDULE_ID 			INTEGER NOT NULL ,
	HEIGHT 					INTEGER,
	WIDTH 					INTEGER,
	LEFT_POS 				INTEGER,
	TOP_POS 				INTEGER,
	TIMER 					INTEGER,
	VIEW_TIMES 				INTEGER,
	CONSTRAINT PK_TB_POPUP_SCHEDULE PRIMARY KEY (SCHEDULE_ID)
);

CREATE TABLE TB_CONTAINER (
	NAME		VARCHAR(30) NOT NULL,
	TYPE		VARCHAR(20) NOT NULL,
	CONSTRAINT PK_TB_CONTAINER  PRIMARY KEY (NAME,TYPE)
);

CREATE TABLE TB_HTML (
	CONTENT_ID          INTEGER NOT NULL,
	TITLE				VARCHAR(50),
	BODY				TEXT,
	CONSTRAINT PK_TB_HTML PRIMARY KEY (CONTENT_ID)
);