INSERT INTO TB_MENU_ITEMS ( MENU_ITEM_ID, LANGUAGE_ID, PARENT, POSITION, MENU_ITEM_TITLE, URL, ENABLED, MARKED, ICON1, ICON2, ITEM_TYPE, OBJ_TYPE ) 
	VALUES ( '/', 'it', NULL, 1, 'Root', NULL, 'T', 'F', NULL, NULL, 'LINK', 0); 

INSERT INTO TB_MENU_ITEMS ( MENU_ITEM_ID, LANGUAGE_ID, PARENT, POSITION, MENU_ITEM_TITLE, URL,ENABLED, MARKED, ICON1, ICON2, ITEM_TYPE, OBJ_TYPE ) 
	VALUES ( '/fpm', 'it', '/', 1, 'FPM', '/fpm/index.xwb', 'T', 'F', NULL, NULL, 'LINK', 0); 

INSERT INTO TB_MENU_ITEMS ( MENU_ITEM_ID, LANGUAGE_ID, PARENT, POSITION, MENU_ITEM_TITLE, URL,ENABLED, MARKED, ICON1, ICON2, ITEM_TYPE, OBJ_TYPE ) 
	VALUES ( '/admin', 'it', '/', 2, 'Administration', NULL, 'T', 'F', NULL, NULL, 'LINK', 0); 

INSERT INTO TB_MENU_ITEMS ( MENU_ITEM_ID, LANGUAGE_ID, PARENT, POSITION, MENU_ITEM_TITLE, URL,ENABLED, MARKED, ICON1, ICON2, ITEM_TYPE, OBJ_TYPE ) 
	VALUES ( '/admin/administration', 'it', '/admin', 1, 'Administration', '/xweb-res/main.xwb', 'T', 'F', NULL, NULL, 'ADMIN', 0); 
