INSERT INTO TB_MENU_ITEM_GROUP (MENU_ITEM_ID, GROUP_ID) VALUES ('/', 'EVERYONE');

INSERT INTO TB_MENU_ITEM_GROUP ( MENU_ITEM_ID, GROUP_ID ) VALUES ( '/fpm', 'FPM_ADMIN'); 
INSERT INTO TB_MENU_ITEM_GROUP ( MENU_ITEM_ID, GROUP_ID ) VALUES ( '/fpm', 'FPM_USER'); 
INSERT INTO TB_MENU_ITEM_GROUP ( MENU_ITEM_ID, GROUP_ID ) VALUES ( '/fpm', 'DEBUG'); 
INSERT INTO TB_MENU_ITEM_GROUP ( MENU_ITEM_ID, GROUP_ID ) VALUES ( '/fpm', 'XWEB_ADMIN'); 

INSERT INTO TB_MENU_ITEM_GROUP ( MENU_ITEM_ID, GROUP_ID ) VALUES ( '/admin/administration', 'XWEB_ADMIN'); 
INSERT INTO TB_MENU_ITEM_GROUP ( MENU_ITEM_ID, GROUP_ID ) VALUES ( '/admin', 'XWEB_ADMIN'); 
