INSERT INTO TB_RESOURCE_COLLECTION ( COLLECTION_NAME, DESCRIPTION, URL_PATTERN, CONSTRAINTS_ENABLED ) 
	VALUES ('administration', 'admin', '/xweb-res', 1);

INSERT INTO TB_RESOURCE_COLLECTION ( COLLECTION_NAME, DESCRIPTION, URL_PATTERN, CONSTRAINTS_ENABLED ) 
	VALUES ('fpm', 'fpm', '/fpm', 1);
	
INSERT INTO TB_RESOURCE_COLLECTION ( COLLECTION_NAME, DESCRIPTION, URL_PATTERN, CONSTRAINTS_ENABLED ) 
	VALUES ('fpm-template', 'fpm-template', '/fpm-template', 1);