INSERT INTO TB_SECURITY_CONSTRAINT ( COLLECTION_NAME, GROUP_ID ) VALUES ('administration', 'XWEB_ADMIN');
INSERT INTO TB_SECURITY_CONSTRAINT ( COLLECTION_NAME, GROUP_ID ) VALUES ('fpm', 'FPM_USER');
INSERT INTO TB_SECURITY_CONSTRAINT ( COLLECTION_NAME, GROUP_ID ) VALUES ('fpm-template', 'XWEB_ADMIN');