INSERT INTO TB_USER_GROUP ( GROUP_ID, USER_ID ) VALUES (
'USER', 'xweb.approver');
INSERT INTO TB_USER_GROUP ( GROUP_ID, USER_ID ) VALUES (
'USER', 'xweb.editor');
INSERT INTO TB_USER_GROUP ( GROUP_ID, USER_ID ) VALUES (
'USER', 'xweb.supervisor');

INSERT INTO TB_USER_GROUP ( GROUP_ID, USER_ID ) VALUES (
'DIARY_APPROVE', 'xweb.approver');
INSERT INTO TB_USER_GROUP ( GROUP_ID, USER_ID ) VALUES (
'DIARY_EDITOR', 'xweb.editor');
INSERT INTO TB_USER_GROUP ( GROUP_ID, USER_ID ) VALUES (
'DIARY_RELEASE', 'xweb.supervisor');
INSERT INTO TB_USER_GROUP ( GROUP_ID, USER_ID ) VALUES (
'NEWS_APPROVE', 'xweb.approver');
INSERT INTO TB_USER_GROUP ( GROUP_ID, USER_ID ) VALUES (
'NEWS_EDITOR', 'xweb.editor');
INSERT INTO TB_USER_GROUP ( GROUP_ID, USER_ID ) VALUES (
'NEWS_RELEASE', 'xweb.supervisor');
INSERT INTO TB_USER_GROUP ( GROUP_ID, USER_ID ) VALUES (
'POLL_APPROVE', 'xweb.approver');
INSERT INTO TB_USER_GROUP ( GROUP_ID, USER_ID ) VALUES (
'POLL_EDITOR', 'xweb.editor');
INSERT INTO TB_USER_GROUP ( GROUP_ID, USER_ID ) VALUES (
'POLL_RELEASE', 'xweb.supervisor');

INSERT INTO TB_USER_GROUP ( GROUP_ID, USER_ID ) VALUES ('MESSAGE_APPROVE', 'xweb.approver');
INSERT INTO TB_USER_GROUP ( GROUP_ID, USER_ID ) VALUES ('MESSAGE_EDITOR', 'xweb.editor');
INSERT INTO TB_USER_GROUP ( GROUP_ID, USER_ID ) VALUES ('MESSAGE_RELEASE', 'xweb.supervisor');
