alter table TB_CONTENT_PERMISSION modify PRINCIPAL VARCHAR2(50);

-- questa FK ci dovrebbe essere già essere ma si è persa tra le varie versioni
-- non lanciare se c'è già nel db
ALTER TABLE TB_NEWSLETTER ADD CONSTRAINT FK_NEWSLETTER_TYPE FOREIGN KEY (MSG_TYPE_ID) REFERENCES TB_NEWSLETTER_TYPE;

-- tolta FK su TB_POOL_USER verso TB_USER_PROFILES
ALTER TABLE TB_POOL_USER DROP CONSTRAINT FK_TB_POOL_USER_TB_USER_PROF;

-- CAMBIO DELLE CHIAVI PRIMARIE PER LE TABELLE TB_NEWS, TB_NEWS_LINK e TB_NEWS_PICTURE
alter table TB_NEWS_LINK drop constraint FK_TB_NEWS;
alter table TB_NEWS_LINK drop constraint PK_TB_NEWS_LINK;

alter table TB_NEWS_PICTURE drop constraint FK_TB_NEWS_PIC;
alter table TB_NEWS_PICTURE drop constraint PK_TB_NEWS_PICTURE;

alter table TB_NEWS drop constraint FK_NEWS_WF_CONTENT_STATUS;
alter table TB_NEWS drop constraint PK_TB_NEWS;

alter table TB_NEWS rename column WF_CONTENT_ID to CONTENT_ID;
alter table TB_NEWS add constraint PK_TB_NEWS primary key (CONTENT_ID);
ALTER TABLE TB_NEWS ADD CONSTRAINT FK_NEWS_WF_CONTENT_STATUS FOREIGN KEY (CONTENT_ID)
		REFERENCES TB_WF_CONTENT_STATUS (WF_CONTENT_ID) ON DELETE CASCADE;

update TB_NEWS_LINK set NEWS_ID=(select CONTENT_ID from TB_NEWS where NEWS_ID=TB_NEWS_LINK.NEWS_ID) 
		where NEWS_ID in (select NEWS_ID from TB_NEWS);
ALTER TABLE TB_NEWS_LINK ADD CONSTRAINT PK_TB_NEWS_LINK PRIMARY KEY (LINK_ID, NEWS_ID);		
ALTER TABLE TB_NEWS_LINK ADD CONSTRAINT FK_TB_NEWS FOREIGN KEY (NEWS_ID)
        REFERENCES TB_NEWS (CONTENT_ID) ON DELETE CASCADE;

update TB_NEWS_PICTURE set NEWS_ID=(select CONTENT_ID from TB_NEWS where NEWS_ID=TB_NEWS_PICTURE.NEWS_ID) 
		where NEWS_ID in (select NEWS_ID from TB_NEWS);
ALTER TABLE TB_NEWS_PICTURE ADD CONSTRAINT PK_TB_NEWS_PICTURE PRIMARY KEY (PICTURE_ID, NEWS_ID);		
ALTER TABLE TB_NEWS_PICTURE ADD CONSTRAINT FK_TB_NEWS_PIC FOREIGN KEY (NEWS_ID)
		REFERENCES TB_NEWS (CONTENT_ID) ON DELETE CASCADE;

ALTER TABLE TB_NEWS MODIFY NEWS_ID NULL;
ALTER TABLE TB_NEWS MODIFY LANGUAGE_ID NULL;
ALTER TABLE TB_NEWS_LINK MODIFY LANGUAGE_ID NULL;
ALTER TABLE TB_NEWS_PICTURE MODIFY LANGUAGE_ID NULL;
/**********************************************************************************
-- se le seguenti colonne non vengono mai utilizzate, decommentare le righe
ALTER TABLE TB_NEWS_PICTURE DROP COLUMN LANGUAGE_ID;

ALTER TABLE TB_NEWS_LINK DROP COLUMN LANGUAGE_ID;

ALTER TABLE TB_NEWS DROP COLUMN LANGUAGE_ID;
ALTER TABLE TB_NEWS DROP COLUMN NEWS_ID;
ALTER TABLE TB_NEWS DROP COLUMN NEWS_URL;
***********************************************************************************/

-- cambio chiave primaria per la tabella TB_POOL e TB_ANSWERS
ALTER TABLE TB_ANSWERS DROP CONSTRAINT FK_TB_POOL;

ALTER TABLE TB_POOL_USER DROP CONSTRAINT FK_TB_POOL_TB_POOL_USER;

ALTER TABLE TB_POOL DROP CONSTRAINT FK_POOL_WF_CONTENT_STATUS;
ALTER TABLE TB_POOL DROP CONSTRAINT PK_TB_POOL;

alter table TB_POOL rename column WF_CONTENT_ID to CONTENT_ID;
alter table TB_POOL add constraint PK_TB_POOL primary key (CONTENT_ID);
ALTER TABLE TB_POOL ADD CONSTRAINT FK_POOL_WF_CONTENT_STATUS FOREIGN KEY (CONTENT_ID)
		REFERENCES TB_WF_CONTENT_STATUS (WF_CONTENT_ID) ON DELETE CASCADE;
		
update TB_ANSWERS set POOL_ID=(select CONTENT_ID from TB_POOL where POOL_ID=TB_ANSWERS.POOL_ID) 
		where POOL_ID in (select POOL_ID from TB_POOL);
ALTER TABLE TB_ANSWERS ADD CONSTRAINT FK_TB_POOL FOREIGN KEY (POOL_ID)
        REFERENCES TB_POOL (CONTENT_ID) ON DELETE CASCADE;

update TB_POOL_USER set POOL_ID=(select CONTENT_ID from TB_POOL where POOL_ID=TB_POOL_USER.POOL_ID) 
		where POOL_ID in (select POOL_ID from TB_POOL);
ALTER TABLE TB_POOL_USER ADD CONSTRAINT FK_TB_POOL_TB_POOL_USER FOREIGN KEY (POOL_ID)
		REFERENCES TB_POOL (CONTENT_ID) ON DELETE CASCADE;

ALTER TABLE TB_POOL MODIFY POOL_ID NULL;
/**********************************************************************************
-- se le seguenti colonne non vengono mai utilizzate, decommentare la riga
ALTER TABLE TB_POOL DROP COLUMN POOL_ID;
***********************************************************************************/

-- CREAZIONE TABELLA TB_POPUP
CREATE TABLE TB_POPUP (
	NAME					VARCHAR2(30),
	CONSTRAINT PK_TB_POPUP
              PRIMARY KEY (NAME)
);

CREATE TABLE TB_POPUP_CONFIGURATION (
	CONTENT_ID 				NUMBER NOT NULL ,
	POPUP_NAME				VARCHAR2(30),
	POSITION 				NUMBER,
	URL 					VARCHAR2(250),
	BODY					CLOB,
	HEIGHT 					NUMBER,
	WIDTH 					NUMBER,
	LEFT 					NUMBER,
	TOP 					NUMBER,
	TIMER 					NUMBER,
	VIEW_TIMES 				NUMBER,
	CONFIGURATION_NAME 		VARCHAR2(30),
	STATUS               	NUMBER(1) DEFAULT 1 NULL,
	CONSTRAINT PK_TB_POPUP_CONFIGURATION
              PRIMARY KEY (CONTENT_ID)
);

ALTER TABLE TB_POPUP_CONFIGURATION
	ADD CONSTRAINT FK_POPUP_CONF_CONTENT
			  FOREIGN KEY (CONTENT_ID)
                             REFERENCES TB_WF_CONTENT_STATUS
                             ON DELETE CASCADE;

ALTER TABLE TB_POPUP_CONFIGURATION
	ADD CONSTRAINT FK_POPUP_CONF_POPUP
			  FOREIGN KEY (POPUP_NAME)
                             REFERENCES TB_POPUP
                             ON DELETE CASCADE;
                             
INSERT INTO TB_FUNCTION_GROUPS ( GROUP_ID, FUNCTION_ID, MODULE_ID ) VALUES (
'NEWS_EDITOR', 'REMOVE_PICTURE', 'NEWS');                             
