SET sql_mode='ANSI_QUOTES';

ALTER TABLE TB_EVENTS DROP FOREIGN KEY "FK_TB_EVENTS";

ALTER TABLE TB_FUNCTION_GROUPS DROP FOREIGN KEY "FK_TR_GROUPS_FUNCTIONS";

ALTER TABLE TB_FUNCTION_GROUPS DROP FOREIGN KEY "FK_TB_FUNCTIONS";

ALTER TABLE TB_FUNCTIONS DROP FOREIGN KEY "FK_TB_MODULES";

ALTER TABLE TB_GROUPS DROP FOREIGN KEY "FK_TB_GROUP_TYPES";

ALTER TABLE TB_MENU_ITEM_GROUP DROP FOREIGN KEY "FK_GROUP_ITEM";

ALTER TABLE TB_MENU_ITEM_GROUP DROP FOREIGN KEY "FK_ITEM_GROUP";

ALTER TABLE TB_MENU_ITEMS DROP FOREIGN KEY "FK_PARENT_CHECK";

ALTER TABLE TB_MODULES DROP FOREIGN KEY "FK_MODULES_TYPES";

ALTER TABLE TB_PAGES DROP FOREIGN KEY "FK_PAGES_TRACKING";

ALTER TABLE TB_USER_GROUP DROP FOREIGN KEY "FK_TB_USER_PROFILES";

ALTER TABLE TB_USER_GROUP DROP FOREIGN KEY "FK_TB_GROUP_ID";

ALTER TABLE TB_USER_PROFILES DROP FOREIGN KEY "FK_USER_TYPE";

ALTER TABLE TB_USER_PROFILES DROP FOREIGN KEY "FK_TB_USER_STATUS";

ALTER TABLE TB_SPECIAL_DATES DROP FOREIGN KEY "FK_SPEC_DATES_REF_CALS";

ALTER TABLE TB_SECURITY_CONSTRAINT DROP FOREIGN KEY "FK_TB_RESOURCE_COLLECTION";

ALTER TABLE TB_SECURITY_CONSTRAINT DROP FOREIGN KEY "FK_TB_CONSTRAINT_GROUP";