DROP TABLE TB_USER_PROPERTY ;

DROP TABLE TB_SPECIAL_DATES ;

DROP TABLE TB_CALENDARS ;

DROP TABLE TB_CALENDAR ;

DROP TABLE TB_HOURS_OF_DAY ;

DROP TABLE TB_OLD_PASSWORDS;

DROP TABLE TB_USER_GROUP ;

DROP TABLE TB_USER_PROFILES ;

DROP TABLE TB_USER_TYPE ;

DROP TABLE TB_USER_STATUS ;

DROP TABLE TB_PAGES ;

DROP TABLE TB_TRACKING ;

DROP TABLE TB_FUNCTION_GROUPS ;

DROP TABLE TB_FUNCTIONS ;

DROP TABLE TB_MODULES ;

DROP TABLE TB_MODULE_TYPES ;

DROP TABLE TB_MENU_ITEM_GROUP ;

DROP TABLE TB_MENU_ITEMS ;

DROP TABLE TB_SECURITY_CONSTRAINT;

DROP TABLE TB_RESOURCE_COLLECTION;

DROP TABLE TB_GROUPS ;

DROP TABLE TB_GROUP_TYPES ;

DROP TABLE TB_EVENTS ;

DROP TABLE TB_EVENT_TYPE ;