CREATE TABLE TB_ANSWERS (
       ANSWERS_ID           INTEGER NOT NULL,
       POLL_ID              INTEGER NOT NULL,
       ANSWER_TEXT          VARCHAR(200),
       HIT                  INTEGER,
       INITIAL_HIT          INTEGER,
       CONSTRAINT PK_ANSWER
              PRIMARY KEY (ANSWERS_ID, POLL_ID)
);


CREATE TABLE TB_CUSTOM_QUERY (
       QUERY_ID             VARCHAR(20) NOT NULL,
       QUERY_TXT            VARCHAR(200) NOT NULL,
       CONSTRAINT PK_TB_CUSTOM_QUERY
              PRIMARY KEY (QUERY_ID)
);


CREATE TABLE TB_NEWS (
       CONTENT_ID        	INTEGER NOT NULL ,
       TITLE                VARCHAR(255),
       SUBTITLE             VARCHAR(255),
       BODY                 CLOB,
       CONSTRAINT PK_TB_NEWS
              PRIMARY KEY (CONTENT_ID)
);


CREATE TABLE TB_NEWS_LINK (
       LINK_ID              INTEGER NOT NULL,
       NEWS_ID              INTEGER NOT NULL,
       URL                  VARCHAR(255),
       NEWS_LINK_TITLE      VARCHAR(255),
       ALT                  VARCHAR(255),
       CONSTRAINT PK_TB_NEWS_LINK
              PRIMARY KEY (LINK_ID, NEWS_ID)
);


CREATE TABLE TB_NEWS_PICTURE (
       PICTURE_ID           INTEGER NOT NULL,
       NEWS_ID              INTEGER NOT NULL,
       URL                  VARCHAR(255),
       ALT                  VARCHAR(255),
       PICTURE_NAME         VARCHAR(255),
       CONSTRAINT PK_TB_NEWS_PICTURE
              PRIMARY KEY (PICTURE_ID, NEWS_ID)
);


CREATE TABLE TB_POLL (
       CONTENT_ID           INTEGER NOT NULL,
       DESCRIPTION          VARCHAR(100),
       QUESTION             VARCHAR(200),
       QUESTION_TYPE        INTEGER,
       CONSTRAINT PK_TB_POLL
              PRIMARY KEY (CONTENT_ID)
);


CREATE TABLE TB_POLL_USER (
       POLL_ID              INTEGER NOT NULL,
       USER_ID              VARCHAR(20) NOT NULL,
       CONSTRAINT PK_TB_POLL_USER PRIMARY KEY (USER_ID, POLL_ID)
);

CREATE TABLE TB_CONTENT (
       CONTENT_ID        INTEGER NOT NULL,
       STATUS_ID         INTEGER NOT NULL,
       CREATION_DATE        TIMESTAMP NOT NULL,
       RELEASE_DATE         TIMESTAMP,
       APPROVAL_DATE        TIMESTAMP,
       PUBLISH_DATE         TIMESTAMP,
       EXPIRATION_DATE      TIMESTAMP,
       DRAFT_DATE           TIMESTAMP,
       DRAFT_USER_ID        VARCHAR(20),
       RELEASE_USER_ID      VARCHAR(20),
       APPROVE_USER_ID      VARCHAR(20),
       MODULE_ID            VARCHAR(50),
       CONSTRAINT PK_TB_CONTENT
              PRIMARY KEY (CONTENT_ID)
);

CREATE TABLE TB_CONTENT_PERMISSION (
       CONTENT_ID               INTEGER NOT NULL,
       PRINCIPAL            	VARCHAR(50) NOT NULL,
       PRINCIPAL_TYPE		    VARCHAR(20) NOT NULL,
       READ_PERMISSION			INTEGER NOT NULL,
       WRITE_PERMISSION			INTEGER NOT NULL,
       CONSTRAINT PK_CNT_PERMISSION PRIMARY KEY (PRINCIPAL, CONTENT_ID, PRINCIPAL_TYPE),
       CONSTRAINT CNT_READ_PERM_CK CHECK (READ_PERMISSION in (0, 1)),
       CONSTRAINT CNT_WRITE_PERM_CK CHECK (WRITE_PERMISSION in (0, 1)),
       CONSTRAINT CNT_PRINC_TYPE_CK CHECK (PRINCIPAL_TYPE in ('USER', 'GROUP'))
);


CREATE TABLE TB_CONTENT_STATUS (
       STATUS_ID         INTEGER NOT NULL,
       DESCRIPTION          VARCHAR(20) NOT NULL,
       CONSTRAINT PK_CONTENT_STATUS
              PRIMARY KEY (STATUS_ID)
);

CREATE TABLE TB_DIARY (
       CONTENT_ID           INTEGER NOT NULL,
       SUBJECT              VARCHAR(100),
       MESSAGE_DATE         TIMESTAMP,
       MESSAGE              CLOB,
       CONSTRAINT PK_TB_DIARY
              PRIMARY KEY (CONTENT_ID)
);

CREATE TABLE TB_MESSAGE (
       CONTENT_ID        	INTEGER NOT NULL,
       SUBJECT              VARCHAR(100),
       MESSAGE_DATE         TIMESTAMP,
       MESSAGE              CLOB,
       CONSTRAINT PK_TB_MESSAGE
              PRIMARY KEY (CONTENT_ID)
);

CREATE TABLE TB_CONTAINER_SCHEDULE (
	SCHEDULE_ID 			INTEGER NOT NULL ,
	SCHEDULE_NAME	 		VARCHAR(250),
	CONTAINER_NAME			VARCHAR(30),
	CONTAINER_TYPE			VARCHAR(20),
	POSITION 				INTEGER,
	URL 					VARCHAR(250),
	CONTENT_ID				INTEGER,
	PUBLISH_DATE        	TIMESTAMP,
    EXPIRATION_DATE      	TIMESTAMP,
	STATUS               	INTEGER DEFAULT 1,
	CONSTRAINT PK_CONT_SCHEDULE PRIMARY KEY (SCHEDULE_ID)
);
                             
CREATE TABLE TB_POPUP_SCHEDULE (
	SCHEDULE_ID 			INTEGER NOT NULL ,
	HEIGHT 					INTEGER,
	WIDTH 					INTEGER,
	LEFT_POS 				INTEGER,
	TOP_POS 				INTEGER,
	TIMER 					INTEGER,
	VIEW_TIMES 				INTEGER,
	CONSTRAINT PK_POPUP_SCHEDULE PRIMARY KEY (SCHEDULE_ID)
);

CREATE TABLE TB_CONTAINER (
	NAME		VARCHAR(30) NOT NULL,
	TYPE		VARCHAR(20) NOT NULL,
	CONSTRAINT PK_TB_CONTAINER PRIMARY KEY (NAME, TYPE)
);

CREATE TABLE TB_HTML (
	CONTENT_ID          INTEGER NOT NULL,
	TITLE				VARCHAR(50),
	BODY				CLOB,
	CONSTRAINT PK_TB_HTML PRIMARY KEY (CONTENT_ID)
);