INSERT INTO TB_CONTENT_STATUS ( STATUS_ID, DESCRIPTION ) VALUES ( 
1, 'DRAFT'); 
INSERT INTO TB_CONTENT_STATUS ( STATUS_ID, DESCRIPTION ) VALUES ( 
2, 'RELEASED'); 
INSERT INTO TB_CONTENT_STATUS ( STATUS_ID, DESCRIPTION ) VALUES ( 
3, 'APPROVED'); 
INSERT INTO TB_CONTENT_STATUS ( STATUS_ID, DESCRIPTION ) VALUES ( 
4, 'PUBLISHED'); 
INSERT INTO TB_CONTENT_STATUS ( STATUS_ID, DESCRIPTION ) VALUES ( 
5, 'EXPIRED'); 
 
