DROP TABLE TB_EVENTS CASCADE CONSTRAINTS;

DROP TABLE TB_EVENT_TYPE CASCADE CONSTRAINTS;

DROP TABLE TB_FUNCTION_GROUPS CASCADE CONSTRAINTS;

DROP TABLE TB_FUNCTIONS CASCADE CONSTRAINTS;

DROP TABLE TB_USER_GROUP CASCADE CONSTRAINTS;

DROP TABLE TB_MENU_ITEM_GROUP CASCADE CONSTRAINTS;

DROP TABLE TB_GROUPS CASCADE CONSTRAINTS;

DROP TABLE TB_GROUP_TYPES CASCADE CONSTRAINTS;

DROP TABLE TB_MENU_ITEMS CASCADE CONSTRAINTS;

DROP TABLE TB_MODULES CASCADE CONSTRAINTS;

DROP TABLE TB_MODULE_TYPES CASCADE CONSTRAINTS;

DROP TABLE TB_PAGES CASCADE CONSTRAINTS;

DROP TABLE TB_TRACKING CASCADE CONSTRAINTS;

DROP TABLE TB_USER_PROFILES CASCADE CONSTRAINTS;

DROP TABLE TB_USER_STATUS CASCADE CONSTRAINTS;

DROP TABLE TB_USER_TYPE CASCADE CONSTRAINTS;

DROP TABLE TB_HOURS_OF_DAY CASCADE CONSTRAINTS;

DROP TABLE TB_SPECIAL_DATES CASCADE CONSTRAINTS;

DROP TABLE TB_CALENDARS CASCADE CONSTRAINTS;

DROP TABLE TB_CALENDAR CASCADE CONSTRAINTS;

DROP TABLE TB_USER_PROPERTY CASCADE CONSTRAINTS;

DROP TABLE TB_RESOURCE_COLLECTION CASCADE CONSTRAINTS;

DROP TABLE TB_SECURITY_CONSTRAINT CASCADE CONSTRAINTS;

DROP TABLE TB_OLD_PASSWORDS CASCADE CONSTRAINTS;