SET sql_mode='ANSI_QUOTES';

ALTER TABLE TB_EVENTS ADD CONSTRAINT "FK_TB_EVENTS" FOREIGN KEY (TYPE_ID) REFERENCES TB_EVENT_TYPE (TYPE_ID) ON DELETE CASCADE;

ALTER TABLE TB_FUNCTION_GROUPS ADD CONSTRAINT "FK_TR_GROUPS_FUNCTIONS" FOREIGN KEY (GROUP_ID) REFERENCES TB_GROUPS (GROUP_ID) ON DELETE CASCADE;

ALTER TABLE TB_FUNCTION_GROUPS ADD CONSTRAINT "FK_TB_FUNCTIONS" FOREIGN KEY (FUNCTION_ID, MODULE_ID) REFERENCES TB_FUNCTIONS (FUNCTION_ID, MODULE_ID) ON DELETE CASCADE;

ALTER TABLE TB_FUNCTIONS ADD CONSTRAINT "FK_TB_MODULES" FOREIGN KEY (MODULE_ID) REFERENCES TB_MODULES (MODULE_ID) ON DELETE CASCADE;

ALTER TABLE TB_GROUPS ADD CONSTRAINT "FK_TB_GROUP_TYPES" FOREIGN KEY (GROUP_TYPE) REFERENCES TB_GROUP_TYPES (GROUP_TYPE) ON DELETE CASCADE;

ALTER TABLE TB_MENU_ITEM_GROUP ADD CONSTRAINT "FK_GROUP_ITEM" FOREIGN KEY (MENU_ITEM_ID) REFERENCES TB_MENU_ITEMS (MENU_ITEM_ID) ON DELETE CASCADE;

ALTER TABLE TB_MENU_ITEM_GROUP ADD CONSTRAINT "FK_ITEM_GROUP" FOREIGN KEY (GROUP_ID) REFERENCES TB_GROUPS (GROUP_ID) ON DELETE CASCADE;

ALTER TABLE TB_MENU_ITEMS ADD CONSTRAINT "FK_PARENT_CHECK" FOREIGN KEY (PARENT) REFERENCES TB_MENU_ITEMS (MENU_ITEM_ID);

ALTER TABLE TB_MODULES ADD CONSTRAINT "FK_MODULES_TYPES" FOREIGN KEY (MODULE_TYPE) REFERENCES TB_MODULE_TYPES (MODULE_TYPE) ON DELETE CASCADE;

ALTER TABLE TB_PAGES ADD CONSTRAINT "FK_PAGES_TRACKING" FOREIGN KEY (TRACKING_ID) REFERENCES TB_TRACKING (TRACKING_ID) ON DELETE CASCADE;

ALTER TABLE TB_USER_GROUP ADD CONSTRAINT "FK_TB_USER_PROFILES" FOREIGN KEY (USER_ID) REFERENCES TB_USER_PROFILES (USER_ID) ON DELETE CASCADE;

ALTER TABLE TB_USER_GROUP ADD CONSTRAINT "FK_TB_GROUP_ID" FOREIGN KEY (GROUP_ID) REFERENCES TB_GROUPS (GROUP_ID) ON DELETE CASCADE;

ALTER TABLE TB_USER_PROFILES ADD CONSTRAINT "FK_USER_TYPE" FOREIGN KEY (USER_TYPE) REFERENCES TB_USER_TYPE (TYPE);

ALTER TABLE TB_USER_PROFILES ADD CONSTRAINT "FK_TB_USER_STATUS" FOREIGN KEY (ID_USER_STATUS) REFERENCES TB_USER_STATUS (ID_USER_STATUS);

ALTER TABLE TB_SPECIAL_DATES ADD CONSTRAINT "FK_SPEC_DATES_REF_CALS" FOREIGN KEY (CALENDAR_ID) REFERENCES TB_CALENDARS (CALENDAR_ID) ON DELETE CASCADE;

ALTER TABLE TB_SECURITY_CONSTRAINT ADD CONSTRAINT "FK_TB_RESOURCE_COLLECTION" FOREIGN KEY (COLLECTION_NAME) REFERENCES TB_RESOURCE_COLLECTION (COLLECTION_NAME) ON DELETE CASCADE;

ALTER TABLE TB_SECURITY_CONSTRAINT ADD CONSTRAINT "FK_TB_CONSTRAINT_GROUP" FOREIGN KEY (GROUP_ID) REFERENCES TB_GROUPS (GROUP_ID) ON DELETE CASCADE;
