ALTER TABLE TB_MENU_ITEMS MODIFY PARENT NULL;
ALTER TABLE TB_MENU_ITEMS ADD ITEM_TYPE VARCHAR2(20) NULL;
ALTER TABLE TB_MENU_ITEMS MODIFY POSITION DEFAULT 1 NULL;

UPDATE TB_MENU_ITEMS SET PARENT = NULL WHERE PARENT = 0 AND MENU_ITEM_ID = 0;
UPDATE TB_MENU_ITEMS SET POSITION = 1 WHERE POSITION = 0;

-- propaga al root item i permessi dei figli
INSERT INTO TB_MENU_ITEM_GROUP (
    SELECT DISTINCT MENU_ID,0,GROUP_ID FROM TB_MENU_ITEM_GROUP ITEMS WHERE ITEMS.MENU_ID IN
    (
        SELECT MENU_ID
        FROM TB_MENU
    )
);

-- aggiunta ON DELETE CASCADE alle constraint di TB_SECURITY_CONSTRAINT
ALTER TABLE TB_SECURITY_CONSTRAINT DROP CONSTRAINT FK_TB_RESOURCE_COLLECTION;
ALTER TABLE TB_SECURITY_CONSTRAINT ADD CONSTRAINT FK_TB_RESOURCE_COLLECTION FOREIGN KEY (COLLECTION_NAME) REFERENCES TB_RESOURCE_COLLECTION ON DELETE CASCADE;
ALTER TABLE TB_SECURITY_CONSTRAINT DROP CONSTRAINT FK_TB_CONSTRAINT_GROUP;
ALTER TABLE TB_SECURITY_CONSTRAINT ADD CONSTRAINT FK_TB_CONSTRAINT_GROUP FOREIGN KEY (GROUP_ID) REFERENCES TB_GROUPS ON DELETE CASCADE;


--- nuovo management utente. hashing password
-- password varchar2(50)
ALTER TABLE TB_USER_PROFILES MODIFY PASSWORD VARCHAR2(50);
-- aggiornamento altre pwd utenti

-- controlli sulla password
ALTER TABLE TB_USER_PROFILES ADD PASSWORD_EXPIRATION_DATE DATE NULL;

CREATE TABLE TB_OLD_PASSWORDS (
	USER_ID		VARCHAR2(20) NOT NULL,
	PASSWORD	VARCHAR2(50) NOT NULL,
	PASSWORD_TIMESTAMP	DATE NOT NULL,
	CONSTRAINT PK_TB_OLD_PASSWORDS
              PRIMARY KEY (USER_ID, PASSWORD, PASSWORD_TIMESTAMP)	
);