CREATE TABLE TB_CALENDAR (
	CALENDAR_DATE 			DATE NOT NULL ,
	DAY NUMBER(2,0) 		NOT NULL ,
	MONTH NUMBER(2,0) 		NOT NULL ,
	YEAR NUMBER(4,0) 		NOT NULL ,
	NOTE 					VARCHAR2(100),
	CONSTRAINT PK_TB_CALENDAR PRIMARY KEY (CALENDAR_DATE) 
);

CREATE TABLE TB_CALENDARS (
	CALENDAR_ID 			VARCHAR2(30) NOT NULL ,
	DESCRIPTION 			VARCHAR2(255),
	CONSTRAINT PK_TB_CALENDARS PRIMARY KEY (CALENDAR_ID) 
);

CREATE TABLE TB_SPECIAL_DATES (
	CALENDAR_DATE 			DATE NOT NULL ,
	CALENDAR_ID 			VARCHAR2(30) NOT NULL ,
	NOTE 					VARCHAR2(255),
	CONSTRAINT PK_TB_SPECIAL_DATES PRIMARY KEY (CALENDAR_DATE, CALENDAR_ID) 
);

CREATE TABLE TB_HOURS_OF_DAY (
	HOUR 					VARCHAR2(2),
	MINUTE	 				VARCHAR2(2)
);

-- per popolare la tabella TB_HOURS_OF_DAY
CREATE OR REPLACE  PROCEDURE FILLS_TB_HOURS_OF_DAY
    as  
  hour NUMBER;
  m    NUMBER;  
begin
  delete TB_HOURS_OF_DAY;
  
  hour := 0;
  m := 0;
  loop
      loop
          insert into TB_HOURS_OF_DAY (HOUR, MINUTE) values (trim(to_char(hour, '09')), trim(to_char(m, '09')));
          m := m + 1;
      exit when m >= 60;
      end loop;
      hour := hour + 1;
      m := 0;
  exit when hour >= 24;
  end loop;
end;
/

alter procedure FILLS_TB_HOURS_OF_DAY compile;

exec FILLS_TB_HOURS_OF_DAY;

commit;
-- fine popolamento tabella TB_HOURS_OF_DAY

ALTER TABLE TB_SPECIAL_DATES ADD CONSTRAINT FK_SPEC_DATES_REF_CAL 
	FOREIGN KEY (CALENDAR_DATE) REFERENCES TB_CALENDAR (CALENDAR_DATE) ON DELETE CASCADE;
	
ALTER TABLE TB_SPECIAL_DATES ADD CONSTRAINT FK_SPEC_DATES_REF_CALS 
	FOREIGN KEY (CALENDAR_ID) REFERENCES TB_CALENDARS (CALENDAR_ID) ON DELETE CASCADE;
	
CREATE TABLE TB_USER_PROPERTY (
	USER_ID					VARCHAR2(20) NOT NULL,
	PROPERTY_NAME			VARCHAR2(20) NOT NULL,
	VALUE					VARCHAR2(255) NULL,
	CONSTRAINT PK_TB_USER_PROPERTY PRIMARY KEY (USER_ID, PROPERTY_NAME)
);	

-- TB_USER_PROFILES
alter table TB_USER_PROFILES modify USER_TYPE DEFAULT 'XWEB_USER';