ALTER TABLE TB_SPECIAL_DATES DROP CONSTRAINT FK_SPEC_DATES_REF_CAL;

-- tabelle per autenticazione
CREATE TABLE TB_RESOURCE_COLLECTION (
		COLLECTION_NAME			VARCHAR2(20) NOT NULL,
		DESCRIPTION				VARCHAR2(200) NULL,
		URL_PATTERN				VARCHAR2(200) NOT NULL,
		CONSTRAINTS_ENABLED		NUMBER(*, 0) DEFAULT 0 NOT NULL,
		CONSTRAINT PK_TB_RESOURCE_COLLECTIONS PRIMARY KEY (COLLECTION_NAME)
);

CREATE TABLE TB_SECURITY_CONSTRAINT (
		COLLECTION_NAME			VARCHAR2(20) NOT NULL,
		GROUP_ID				VARCHAR2(50) NOT NULL,
		CONSTRAINT PK_TB_SECURITY_CONSTRAINTS PRIMARY KEY (COLLECTION_NAME, GROUP_ID)
);

ALTER TABLE TB_SECURITY_CONSTRAINT ADD CONSTRAINT FK_TB_RESOURCE_COLLECTION
		FOREIGN KEY (COLLECTION_NAME) REFERENCES TB_RESOURCE_COLLECTION;

ALTER TABLE TB_SECURITY_CONSTRAINT ADD CONSTRAINT FK_TB_CONSTRAINT_GROUP
		FOREIGN KEY (GROUP_ID) REFERENCES TB_GROUPS;
		
INSERT INTO TB_RESOURCE_COLLECTION ( COLLECTION_NAME, DESCRIPTION, URL_PATTERN, CONSTRAINTS_ENABLED ) 
	VALUES ('administration', 'admin', '/xweb-res', 1);

INSERT INTO TB_SECURITY_CONSTRAINT ( COLLECTION_NAME, GROUP_ID ) VALUES ('administration', 'XWEB_ADMIN');

-- Modulo di Autorizzazione
INSERT INTO TB_MODULES ( MODULE_TYPE, ADMIN_URI, MODULE_TITLE, MODULE_ID, CONTENT_LOCATION, DESCRIPTION ) VALUES (1, '/xweb-res/authorization/resource_collections.xwb', 'Sicurezza', 'AUTH', NULL, 'Permette di impostare i vincoli di accesso per i gruppi');

INSERT INTO TB_FUNCTIONS (FUNCTION_ID, MODULE_ID, FUNCTION_URI, FUNCTION_TITLE, WF_MGR_AUTO) VALUES ('VISUALIZZA', 'AUTH', NULL, 'Visualizza', NULL);
INSERT INTO TB_FUNCTIONS (FUNCTION_ID, MODULE_ID, FUNCTION_URI, FUNCTION_TITLE, WF_MGR_AUTO) VALUES ('CREATE', 'AUTH', NULL, 'Crea', NULL);
INSERT INTO TB_FUNCTIONS (FUNCTION_ID, MODULE_ID, FUNCTION_URI, FUNCTION_TITLE, WF_MGR_AUTO) VALUES ('DELETE', 'AUTH', NULL, 'Elimina', NULL);
INSERT INTO TB_FUNCTIONS (FUNCTION_ID, MODULE_ID, FUNCTION_URI, FUNCTION_TITLE, WF_MGR_AUTO) VALUES ('UPDATE', 'AUTH', NULL, 'Modifica', NULL);

INSERT INTO TB_FUNCTION_GROUPS (GROUP_ID, FUNCTION_ID, MODULE_ID) VALUES ('XWEB_ADMIN', 'DELETE', 'AUTH');
INSERT INTO TB_FUNCTION_GROUPS (GROUP_ID, FUNCTION_ID, MODULE_ID) VALUES ('XWEB_ADMIN', 'VISUALIZZA', 'AUTH');
INSERT INTO TB_FUNCTION_GROUPS (GROUP_ID, FUNCTION_ID, MODULE_ID) VALUES ('XWEB_ADMIN', 'CREATE', 'AUTH');
INSERT INTO TB_FUNCTION_GROUPS (GROUP_ID, FUNCTION_ID, MODULE_ID) VALUES ('XWEB_ADMIN', 'UPDATE', 'AUTH');		