DROP TABLE TB_ANSWERS CASCADE CONSTRAINTS;

DROP TABLE TB_CUSTOM_QUERY CASCADE CONSTRAINTS;

DROP TABLE TB_POLL_USER CASCADE CONSTRAINTS;

DROP TABLE TB_POLL CASCADE CONSTRAINTS;

DROP TABLE TB_NEWS_PICTURE CASCADE CONSTRAINTS;

DROP TABLE TB_NEWS_LINK CASCADE CONSTRAINTS;

DROP TABLE TB_NEWS CASCADE CONSTRAINTS;

DROP TABLE TB_CONTENT_STATUS CASCADE CONSTRAINTS;

DROP TABLE TB_CONTENT CASCADE CONSTRAINTS;

DROP TABLE TB_CONTENT_PERMISSION CASCADE CONSTRAINTS;

DROP TABLE TB_DIARY CASCADE CONSTRAINTS;

DROP TABLE TB_MESSAGE CASCADE CONSTRAINTS;

DROP TABLE TB_CONTAINER_SCHEDULE CASCADE CONSTRAINTS;

DROP TABLE TB_POPUP_SCHEDULE CASCADE CONSTRAINTS;

DROP TABLE TB_CONTAINER CASCADE CONSTRAINTS;

DROP TABLE TB_HTML CASCADE CONSTRAINTS;