CREATE TABLE TB_EVENT_TYPE (
       TYPE_ID              NUMBER(*, 0) NOT NULL,
       DESCRIPTION          VARCHAR2(250) NULL,
       CONSTRAINT PK_TAB_ENV_EVENT_TYPE
              PRIMARY KEY (TYPE_ID)
);


CREATE TABLE TB_EVENTS (
       EVENT_TIME           DATE NOT NULL,
       USER_ID              VARCHAR2(20) NOT NULL,
       TYPE_ID              NUMBER(*, 0) NULL,
       DESCRIPTION          VARCHAR2(250) NULL,
       CONSTRAINT PK_TB_ENV_EVENTS
              PRIMARY KEY (EVENT_TIME, USER_ID)
);

CREATE TABLE TB_FUNCTION_GROUPS (
       GROUP_ID             VARCHAR2(50) NOT NULL,
       FUNCTION_ID          VARCHAR2(50) NOT NULL,
       MODULE_ID            VARCHAR2(50) NOT NULL,
       CONSTRAINT PK_TB_ENV_FUNCTION_PER_GROUP
              PRIMARY KEY (GROUP_ID, FUNCTION_ID, MODULE_ID)
);


CREATE TABLE TB_FUNCTIONS (
       FUNCTION_ID          VARCHAR2(50) NOT NULL,
       MODULE_ID            VARCHAR2(50) NOT NULL,
       FUNCTION_URI         VARCHAR2(250) NULL,
       FUNCTION_TITLE       VARCHAR2(250) NULL,
       WF_MGR_AUTO          NUMBER(*, 0) NULL,
       CONSTRAINT PK_TB_ENV_FUNCTIONS
              PRIMARY KEY (FUNCTION_ID, MODULE_ID)
);

CREATE TABLE TB_GROUP_TYPES (
       GROUP_TYPE           NUMBER(*, 0) NOT NULL,
       DESCRIPTION          VARCHAR2(200) NULL,
       ADMIN_PAGE_URL		VARCHAR2(100) NOT NULL,
       CLASSNAME			VARCHAR2(100) NULL,
       CONSTRAINT PK_TB_GROUP_TYPES
              PRIMARY KEY (GROUP_TYPE)
);


CREATE TABLE TB_GROUPS (
       GROUP_ID             VARCHAR2(50) NOT NULL,
       GROUP_TYPE           NUMBER(*, 0) NULL,
       DESCRIPTION          VARCHAR2(200) NULL,
       RULE		            VARCHAR2(500) NULL,
       CONSTRAINT PK_TB_GROUPS
              PRIMARY KEY (GROUP_ID)
);


CREATE TABLE TB_MENU_ITEM_GROUP (
       MENU_ITEM_ID         VARCHAR2(256) NOT NULL,
       GROUP_ID             VARCHAR2(50) NOT NULL,
       CONSTRAINT PK_TB_MENU_ITEM_GROUP
              PRIMARY KEY (MENU_ITEM_ID, GROUP_ID)
);


CREATE TABLE TB_MENU_ITEMS (
       MENU_ITEM_ID         VARCHAR2(256) NOT NULL,
       LANGUAGE_ID          VARCHAR2(2) NOT NULL,
       PARENT               VARCHAR2(256) NULL,
       POSITION             NUMBER(*, 0) DEFAULT 1 NULL,
       MENU_ITEM_TITLE      VARCHAR2(250) NULL,
       URL                  VARCHAR2(250) NULL,
       ENABLED              VARCHAR2(1) DEFAULT 'T' NOT NULL
                                   CONSTRAINT CHK_MARKED
                                          CHECK (ENABLED IN ('T','F')),
       MARKED               VARCHAR2(1) DEFAULT 'F' NOT NULL
                                   CONSTRAINT CHK_ENABLED
                                          CHECK (MARKED IN ('T','F')),
       ICON1                VARCHAR2(250) NULL,
       ICON2                VARCHAR2(250) NULL,
       ITEM_TYPE			VARCHAR2(20) NULL,
       OBJ_TYPE             NUMBER(*, 0) DEFAULT 0 NOT NULL,
       CONSTRAINT PK_TB_MENU_ITEMS
              PRIMARY KEY (MENU_ITEM_ID)
);


CREATE TABLE TB_MODULE_TYPES (
       MODULE_TYPE          NUMBER(*, 0) NOT NULL,
       DESCRIPTION          VARCHAR2(200) NULL,
       CONSTRAINT PK_TB_MODULE_TYPE
              PRIMARY KEY (MODULE_TYPE)
);


CREATE TABLE TB_MODULES (
       MODULE_TYPE          NUMBER(*, 0) NULL,
       ADMIN_URI            VARCHAR2(200) NULL,
       MODULE_TITLE         VARCHAR2(250) NULL,
       MODULE_ID            VARCHAR2(50) NOT NULL,
       CONTENT_LOCATION     VARCHAR2(100) NULL,
       DESCRIPTION          VARCHAR2(200) NULL,
       ICON1				VARCHAR2(250) NULL,
       ICON2				VARCHAR2(250) NULL,
       CONSTRAINT PK_TB_MODULES
              PRIMARY KEY (MODULE_ID)
);

CREATE TABLE TB_PAGES (
       ACCESS_TIME          DATE NOT NULL,
       PAGE_NAME            VARCHAR2(80) NOT NULL,
       SEQUENCE_NUMBER      NUMBER(*, 0) NOT NULL,
       TRACKING_ID          NUMBER(*, 0) NOT NULL,
       REFERRER             VARCHAR2(80) NULL,
       QUERY_STRING         VARCHAR2(80) NULL,
       CONSTRAINT PK_TB_PAGES
              PRIMARY KEY (SEQUENCE_NUMBER, TRACKING_ID)
);

CREATE TABLE TB_USER_GROUP (
       GROUP_ID             VARCHAR2(50) NOT NULL,
       USER_ID              VARCHAR2(20) NOT NULL,
       CONSTRAINT PK_TB_ENV_USER_PER_GROUP
              PRIMARY KEY (GROUP_ID, USER_ID)
);

CREATE TABLE TB_USER_PROFILES (
       USER_ID              VARCHAR2(20) NOT NULL,
       PASSWORD             VARCHAR2(50) NULL,
       FIRSTNAME            VARCHAR2(50) NULL,
       LASTNAME             VARCHAR2(50) NULL,
       EMAIL                VARCHAR2(40) NULL,
       LANGUAGE				CHAR(2) DEFAULT 'it' NULL,
	   COUNTRY 				CHAR(2) DEFAULT 'IT' NULL,
       PHONE                VARCHAR2(20) NULL,
       ADDRESS              VARCHAR2(50) NULL,
       CITY                 VARCHAR2(50) NULL,
       PROV                 VARCHAR2(4) NULL,
       ZIPCODE              VARCHAR2(10) NULL,
       STATE          		VARCHAR2(20) NULL,
       MOBILE               VARCHAR2(20) NULL,
       FAX                  VARCHAR2(20) NULL,
       BIRTHDATE            DATE NULL,
       GENDER               CHAR(1) NULL,
       EXPIRATION_DATE      DATE NULL,
       USER_TABLE_NAME      VARCHAR2(50) NULL,
       ID_USER_STATUS       NUMBER(*, 0) NULL,
       HOMEPAGE             VARCHAR2(255) NULL,
       USER_TYPE            VARCHAR2(20) DEFAULT 'XWEB_USER' NULL,
       PASSWORD_EXPIRATION_DATE DATE NULL,
       CONSTRAINT PK_TB_ENV_USER_PROFILES
              PRIMARY KEY (USER_ID)
);


CREATE TABLE TB_USER_STATUS (
       ID_USER_STATUS       NUMBER(*, 0) NOT NULL,
       DESCRIPTION          VARCHAR2(200) NOT NULL,
       CONSTRAINT PK_TB_USER_STATUS
              PRIMARY KEY (ID_USER_STATUS)
);


CREATE TABLE TB_USER_TYPE (
       TYPE                 VARCHAR2(20) NOT NULL,
       CLASSNAME            VARCHAR2(100) NULL,
       CONSTRAINT PK_TB_USER_TYPE
              PRIMARY KEY (TYPE)
);

CREATE TABLE TB_TRACKING (
       USER_ID              VARCHAR2(20) NULL,
       SESSION_ID           VARCHAR2(100) NOT NULL,
       SESSION_START        DATE NOT NULL,
       SESSION_END          DATE NULL,
       TRACKING_ID          NUMBER(*, 0) NOT NULL,
       UNIQUE_IP            VARCHAR2(15) NULL,
       PLATFORM             VARCHAR2(50) NULL,
       SCREEN_SIZE          VARCHAR2(15) NULL,
       BROWSER              VARCHAR2(50) NULL,
       USER_AGENT           VARCHAR2(150) NULL,
       BROWSER_NAME         VARCHAR2(30) NULL,
       BROWSER_VERSION      VARCHAR2(5) NULL,
       CONSTRAINT PK_TB_TRACKING PRIMARY KEY (TRACKING_ID)
);

/*** Tabelle per statistiche ***/
CREATE TABLE TB_CALENDAR (
	CALENDAR_DATE 			DATE NOT NULL ,
	DAY 					NUMBER(*, 0) NOT NULL ,
	MONTH 					NUMBER(*, 0) NOT NULL ,
	YEAR 					NUMBER(*, 0) NOT NULL ,
	NOTE 					VARCHAR2(100),
	CONSTRAINT PK_TB_CALENDAR PRIMARY KEY (CALENDAR_DATE)
);

CREATE TABLE TB_CALENDARS (
	CALENDAR_ID 			VARCHAR2(30) NOT NULL ,
	DESCRIPTION 			VARCHAR2(255),
	CONSTRAINT PK_TB_CALENDARS PRIMARY KEY (CALENDAR_ID)
);

CREATE TABLE TB_SPECIAL_DATES (
	CALENDAR_DATE 			DATE NOT NULL ,
	CALENDAR_ID 			VARCHAR2(30) NOT NULL ,
	NOTE 					VARCHAR2(255),
	CONSTRAINT PK_TB_SPECIAL_DATES PRIMARY KEY (CALENDAR_DATE, CALENDAR_ID)
);

CREATE TABLE TB_HOURS_OF_DAY (
	HOUR 					VARCHAR2(2),
	MINUTE 					VARCHAR2(2)
);

CREATE TABLE TB_USER_PROPERTY (
	USER_ID					VARCHAR2(20) NOT NULL,
	PROPERTY_NAME			VARCHAR2(20) NOT NULL,
	VALUE					VARCHAR2(255) NULL,
	CONSTRAINT PK_TB_USER_PROPERTY PRIMARY KEY (USER_ID, PROPERTY_NAME)
);


CREATE TABLE TB_RESOURCE_COLLECTION (
		COLLECTION_NAME			VARCHAR2(20) NOT NULL,
		DESCRIPTION				VARCHAR2(200) NULL,
		URL_PATTERN				VARCHAR2(200) NOT NULL,
		CONSTRAINTS_ENABLED		NUMBER(*, 0) DEFAULT 0 NOT NULL,
		CONSTRAINT PK_TB_RESOURCE_COLLECTIONS PRIMARY KEY (COLLECTION_NAME)
);

CREATE TABLE TB_SECURITY_CONSTRAINT (
		COLLECTION_NAME			VARCHAR2(20) NOT NULL,
		GROUP_ID				VARCHAR2(50) NOT NULL,
		CONSTRAINT PK_TB_SECURITY_CONSTRAINTS PRIMARY KEY (COLLECTION_NAME, GROUP_ID)
);

CREATE TABLE TB_OLD_PASSWORDS (
	USER_ID		VARCHAR2(20) NOT NULL,
	PASSWORD	VARCHAR2(50) NOT NULL,
	PASSWORD_TIMESTAMP	DATE NOT NULL,
	CONSTRAINT PK_TB_OLD_PASSWORDS
              PRIMARY KEY (USER_ID, PASSWORD, PASSWORD_TIMESTAMP)	
);