CREATE TABLE TB_ANSWERS (
       ANSWERS_ID           NUMBER(*, 0) NOT NULL,
       POLL_ID              NUMBER(*, 0) NOT NULL,
       ANSWER_TEXT          VARCHAR2(200) NULL,
       HIT                  NUMBER(*, 0) NULL,
       INITIAL_HIT          NUMBER(*, 0) NULL,
       CONSTRAINT PK_ANSWER
              PRIMARY KEY (ANSWERS_ID, POLL_ID)
);


CREATE TABLE TB_CUSTOM_QUERY (
       QUERY_ID             VARCHAR2(20) NOT NULL,
       QUERY_TXT            VARCHAR2(200) NOT NULL,
       CONSTRAINT PK_TB_CUSTOM_QUERY
              PRIMARY KEY (QUERY_ID)
);


CREATE TABLE TB_NEWS (
       CONTENT_ID        	NUMBER(*, 0) NOT NULL ,
       TITLE                VARCHAR2(255) NULL,
       SUBTITLE             VARCHAR2(255) NULL,
       BODY                 CLOB NULL,
       CONSTRAINT PK_TB_NEWS
              PRIMARY KEY (CONTENT_ID)
);


CREATE TABLE TB_NEWS_LINK (
       LINK_ID              NUMBER(*, 0) NOT NULL,
       NEWS_ID              NUMBER(*, 0) NOT NULL,
       URL                  VARCHAR2(255) NULL,
       NEWS_LINK_TITLE      VARCHAR2(255) NULL,
       ALT                  VARCHAR2(255) NULL,
       CONSTRAINT PK_TB_NEWS_LINK
              PRIMARY KEY (LINK_ID, NEWS_ID)
);


CREATE TABLE TB_NEWS_PICTURE (
       PICTURE_ID           NUMBER(*, 0) NOT NULL,
       NEWS_ID              NUMBER(*, 0) NOT NULL,
       URL                  VARCHAR2(255) NULL,
       ALT                  VARCHAR2(255) NULL,
       PICTURE_NAME         VARCHAR2(255) NULL,
       CONSTRAINT PK_TB_NEWS_PICTURE
              PRIMARY KEY (PICTURE_ID, NEWS_ID)
);


CREATE TABLE TB_POLL (
       CONTENT_ID           NUMBER(*, 0) NOT NULL,
       DESCRIPTION          VARCHAR2(100) NULL,
       QUESTION             VARCHAR2(200) NULL,
       QUESTION_TYPE        NUMBER(*, 0) NULL,
       CONSTRAINT PK_TB_POLL
              PRIMARY KEY (CONTENT_ID)
);


CREATE TABLE TB_POLL_USER (
       POLL_ID              NUMBER(*, 0) NOT NULL,
       USER_ID              VARCHAR2(20) NOT NULL,
       CONSTRAINT PK_TB_POLL_USER PRIMARY KEY (USER_ID, POLL_ID)
);

CREATE TABLE TB_CONTENT (
       CONTENT_ID        NUMBER(*, 0) NOT NULL,
       STATUS_ID         NUMBER(*, 0) NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       RELEASE_DATE         DATE NULL,
       APPROVAL_DATE        DATE NULL,
       PUBLISH_DATE         DATE NULL,
       EXPIRATION_DATE      DATE NULL,
       DRAFT_DATE           DATE NULL,
       DRAFT_USER_ID        VARCHAR2(20) NULL,
       RELEASE_USER_ID      VARCHAR2(20) NULL,
       APPROVE_USER_ID      VARCHAR2(20) NULL,
       MODULE_ID            VARCHAR2(50) NULL,
       CONSTRAINT PK_TB_CONTENT
              PRIMARY KEY (CONTENT_ID)
);

CREATE TABLE TB_CONTENT_PERMISSION (
       CONTENT_ID               NUMBER(*, 0) NOT NULL,
       PRINCIPAL            	VARCHAR2(50) NOT NULL,
       PRINCIPAL_TYPE		    VARCHAR2(20) NOT NULL,
       READ_PERMISSION			NUMBER(*, 0) NOT NULL,
       WRITE_PERMISSION			NUMBER(*, 0) NOT NULL,
       CONSTRAINT PK_TB_CONTENT_PERMISSION PRIMARY KEY (PRINCIPAL, CONTENT_ID, PRINCIPAL_TYPE),
       CONSTRAINT CONTENT_READ_PERMISSION_CHECK CHECK (READ_PERMISSION in (0, 1)),
       CONSTRAINT CONTENT_WRITE_PERMISSION_CHECK CHECK (WRITE_PERMISSION in (0, 1)),
       CONSTRAINT CONTENT_PRINCIPAL_TYPE_CHECK CHECK (PRINCIPAL_TYPE in ('USER', 'GROUP'))
);


CREATE TABLE TB_CONTENT_STATUS (
       STATUS_ID         NUMBER(*, 0) NOT NULL,
       DESCRIPTION          VARCHAR2(20) NOT NULL,
       CONSTRAINT PK_TB_CONTENT_STATUS
              PRIMARY KEY (STATUS_ID)
);

CREATE TABLE TB_DIARY (
       CONTENT_ID           NUMBER(*, 0) NOT NULL,
       SUBJECT              VARCHAR2(100) NULL,
       MESSAGE_DATE         DATE NULL,
       MESSAGE              CLOB NULL,
       CONSTRAINT PK_TB_DIARY
              PRIMARY KEY (CONTENT_ID)
);

CREATE TABLE TB_MESSAGE (
       CONTENT_ID        	NUMBER(*, 0) NOT NULL,
       SUBJECT              VARCHAR2(100) NULL,
       MESSAGE_DATE         DATE NULL,
       MESSAGE              CLOB NULL,
       CONSTRAINT PK_TB_MESSAGE
              PRIMARY KEY (CONTENT_ID)
);

CREATE TABLE TB_CONTAINER_SCHEDULE (
	SCHEDULE_ID 			NUMBER(*, 0) NOT NULL ,
	SCHEDULE_NAME	 		VARCHAR2(250),
	CONTAINER_NAME			VARCHAR2(30),
	CONTAINER_TYPE			VARCHAR2(20),
	POSITION 				NUMBER(*, 0),
	URL 					VARCHAR2(250),
	CONTENT_ID				NUMBER(*, 0),
	PUBLISH_DATE        	DATE NULL,
    EXPIRATION_DATE      	DATE NULL,
	STATUS               	NUMBER(*, 0) DEFAULT 1 NULL,
	CONSTRAINT PK_TB_CONTAINER_SCHEDULE PRIMARY KEY (SCHEDULE_ID)
);
                             
CREATE TABLE TB_POPUP_SCHEDULE (
	SCHEDULE_ID 			NUMBER(*, 0) NOT NULL ,
	HEIGHT 					NUMBER(*, 0),
	WIDTH 					NUMBER(*, 0),
	LEFT_POS 				NUMBER(*, 0),
	TOP_POS 				NUMBER(*, 0),
	TIMER 					NUMBER(*, 0),
	VIEW_TIMES 				NUMBER(*, 0),
	CONSTRAINT PK_TB_POPUP_SCHEDULE PRIMARY KEY (SCHEDULE_ID)
);

CREATE TABLE TB_CONTAINER (
	NAME		VARCHAR2(30) NOT NULL,
	TYPE		VARCHAR2(20) NOT NULL,
	CONSTRAINT PK_TB_CONTAINER  PRIMARY KEY (NAME, TYPE)
);

CREATE TABLE TB_HTML (
	CONTENT_ID          NUMBER(*, 0) NOT NULL,
	TITLE				VARCHAR2(50),
	BODY				CLOB,
	CONSTRAINT PK_TB_HTML PRIMARY KEY (CONTENT_ID)
);