INSERT INTO TB_MODULE_TYPES ( MODULE_TYPE, DESCRIPTION ) VALUES ( 
1, 'SYSTEM'); 
INSERT INTO TB_MODULE_TYPES ( MODULE_TYPE, DESCRIPTION ) VALUES ( 
2, 'CMS'); 
INSERT INTO TB_MODULE_TYPES ( MODULE_TYPE, DESCRIPTION ) VALUES ( 
4, 'CUSTOM'); 
 
